angular.module('kityminderEditor').factory('agentSessionI18n', [
	'config',
	function(config) {
		var en = {
			provider: 'Provider', switchProvider: 'Switch provider', collapseControlBar: 'Collapse agent controls',
			expandControlBar: 'Expand agent controls', model: 'Model', effort: 'Effort', defaultEffort: 'Default', signIn: 'Sign in',
			instruction: 'Follow-up request', instructionPlaceholder: 'Ask for follow-up changes',
			send: 'Send', sending: 'Sending…', append: 'Append', interrupt: 'Interrupt', install: 'Install', cancel: 'Cancel',
			installTitle: 'Install Provider', close: 'Close', history: 'Session history', records: 'records',
			loading: 'Loading…', noSessions: 'No sessions yet', orphan: 'The original node is gone; history is preserved.',
			requested: 'Requested', effective: 'Effective', artifacts: 'Artifacts', copySessionId: 'Copy session ID',
			loadMore: 'Load more', missing: 'Missing', installed_inactive: 'Installed', ready: 'Ready',
			auth_required: 'Sign in required', degraded: 'Degraded', incompatible: 'Incompatible', failed: 'Failed',
			loadingState: 'Loading', unavailable: 'Unavailable', dirty: 'Save the mind map before sending.',
			active: 'Running', idle: 'Idle', error: 'Error', dismiss: '×', copyDone: 'Copied',
			allocated: 'Allocated', starting: 'Starting', running: 'Running',
			interrupting: 'Interrupting', interrupted: 'Interrupted',
			completed: 'Completed', cancelled: 'Cancelled',
			createdAt: 'Created', nodeId: 'Node ID', level: 'Level', childCount: 'Children', tags: 'Tags',
			taskStatus: 'Task status', taskLabels: 'Task labels', sidecarState: 'Sidecar state', diagnostic: 'Diagnostic',
			sessionTrace: 'Session trace', noSessionRecord: 'No session record', executionState: 'Execution state',
			worker: 'Worker', leaseUntil: 'Lease expires', failureReason: 'Failure reason',
			claimed: 'Running', done: 'Completed', released: 'Released', failedState: 'Failed', leaseExpired: 'Lease expired',
			pending: 'Pending', kmUnavailable: 'KM execution unavailable', nonTask: 'Not a task node', defaultModel: 'Default model',
			activity: 'Activity', activityOverview: 'Active sessions', activeTasks: 'active tasks',
			activeSessionsCount: 'active sessions', noActiveTasks: 'No active agent sessions',
			sessionDetail: 'Session detail', backToSessions: 'Back', updatedAt: 'Updated', executionId: 'Execution ID',
			realtimeEvents: 'Live session events', liveUpdating: 'Live', noRealtimeEvents: 'No live details yet',
				approvalTitle: 'Provider request', response: 'Response', allow: 'Allow', deny: 'Deny', retry: 'Retry',
				installOpening: 'Downloading Provider Runtime', installWaiting: 'Installing Provider Runtime',
				installVerifying: 'Verifying Provider Runtime', installCompleted: 'Installed successfully', installFailed: 'Installation failed',
				mcpReady: 'KM MCP connected', mcpConnecting: 'Connecting to KM MCP…',
				mcpReconnecting: 'Reconnecting to KM MCP…', mcpUnavailable: 'KM MCP unavailable',
				reconnectMcp: 'Reconnect', mcpOperationFailed: 'The KM MCP connection was interrupted. Reconnect, then retry the operation.',
				mcpReconnectedRetry: 'KM MCP is connected again. Retry the previous operation.',
				requestTimedOut: 'The request timed out. Retry is safe; duplicate submissions are prevented.',
				toolPermissions: 'Tool permissions', elevatedRisk: 'Elevated', confirm: 'Confirm',
				permissionConfirmTitle: 'Confirm elevated permissions',
				permissionConfirmMessage: 'This mode expands tool access. Confirm before applying it to the next turn.'
		};
		var uiTranslations = {
			de: { signIn: 'Anmelden', createdAt: 'Erstellt', nodeId: 'Knoten-ID', level: 'Ebene', childCount: 'Unterknoten', tags: 'Tags', taskStatus: 'Aufgabenstatus', taskLabels: 'Aufgabenlabels', sidecarState: 'Begleitstatus', diagnostic: 'Diagnose', sessionTrace: 'Sitzungsverfolgung', noSessionRecord: 'Kein Sitzungsdatensatz', executionState: 'Ausführungsstatus', worker: 'Bearbeiter', leaseUntil: 'Lease endet', failureReason: 'Fehlergrund', claimed: 'In Ausführung', done: 'Abgeschlossen', released: 'Freigegeben', failedState: 'Fehlgeschlagen', leaseExpired: 'Lease abgelaufen', pending: 'Ausstehend', kmUnavailable: 'KM-Ausführung nicht verfügbar', nonTask: 'Kein Aufgabenknoten', defaultModel: 'Standardmodell', activity: 'Aktivität', activityOverview: 'Aktive Sitzungen', activeTasks: 'aktive Aufgaben', noActiveTasks: 'Keine aktiven Sitzungen oder beanspruchten Aufgaben', approvalTitle: 'Anbieteranfrage', response: 'Antwort', allow: 'Zulassen', deny: 'Ablehnen', allocated: 'Zugeteilt', starting: 'Wird gestartet', running: 'Wird ausgeführt', interrupting: 'Wird unterbrochen', interrupted: 'Unterbrochen', completed: 'Abgeschlossen', cancelled: 'Abgebrochen' },
			es: { signIn: 'Iniciar sesión', createdAt: 'Creado', nodeId: 'ID del nodo', level: 'Nivel', childCount: 'Hijos', tags: 'Etiquetas', taskStatus: 'Estado de tarea', taskLabels: 'Etiquetas de tarea', sidecarState: 'Estado auxiliar', diagnostic: 'Diagnóstico', sessionTrace: 'Trazabilidad de sesión', noSessionRecord: 'Sin registro de sesión', executionState: 'Estado de ejecución', worker: 'Ejecutor', leaseUntil: 'Fin del arrendamiento', failureReason: 'Motivo del fallo', claimed: 'En ejecución', done: 'Completado', released: 'Liberado', failedState: 'Fallido', leaseExpired: 'Arrendamiento vencido', pending: 'Pendiente', kmUnavailable: 'Ejecución KM no disponible', nonTask: 'No es un nodo de tarea', defaultModel: 'Modelo predeterminado', activity: 'Actividad', activityOverview: 'Sesiones activas', activeTasks: 'tareas activas', noActiveTasks: 'No hay sesiones activas ni tareas reclamadas', approvalTitle: 'Solicitud del proveedor', response: 'Respuesta', allow: 'Permitir', deny: 'Denegar', allocated: 'Asignado', starting: 'Iniciando', running: 'En ejecución', interrupting: 'Interrumpiendo', interrupted: 'Interrumpido', completed: 'Completado', cancelled: 'Cancelado' },
			fr: { signIn: "Se connecter", createdAt: "Créé", nodeId: "ID du nœud", level: "Niveau", childCount: "Enfants", tags: "Étiquettes", taskStatus: "État de la tâche", taskLabels: "Étiquettes de tâche", sidecarState: "État auxiliaire", diagnostic: "Diagnostic", sessionTrace: "Traçabilité de session", noSessionRecord: "Aucun enregistrement de session", executionState: "État d’exécution", worker: "Exécutant", leaseUntil: "Fin du bail", failureReason: "Motif de l’échec", claimed: "En cours", done: "Terminé", released: "Libéré", failedState: "Échec", leaseExpired: "Bail expiré", pending: "En attente", kmUnavailable: "Exécution KM indisponible", nonTask: "Pas un nœud de tâche", defaultModel: "Modèle par défaut", activity: "Activité", activityOverview: "Sessions actives", activeTasks: "tâches actives", noActiveTasks: "Aucune session active ni tâche réservée", approvalTitle: "Demande du fournisseur", response: "Réponse", allow: "Autoriser", deny: "Refuser", allocated: "Attribué", starting: "Démarrage", running: "En cours", interrupting: "Interruption en cours", interrupted: "Interrompu", completed: "Terminé", cancelled: "Annulé" },
			it: { signIn: 'Accedi', createdAt: 'Creato', nodeId: 'ID nodo', level: 'Livello', childCount: 'Figli', tags: 'Etichette', taskStatus: 'Stato attività', taskLabels: 'Etichette attività', sidecarState: 'Stato ausiliario', diagnostic: 'Diagnostica', sessionTrace: 'Traccia sessione', noSessionRecord: 'Nessun record di sessione', executionState: 'Stato esecuzione', worker: 'Esecutore', leaseUntil: 'Scadenza lease', failureReason: 'Motivo errore', claimed: 'In esecuzione', done: 'Completato', released: 'Rilasciato', failedState: 'Non riuscito', leaseExpired: 'Lease scaduto', pending: 'In attesa', kmUnavailable: 'Esecuzione KM non disponibile', nonTask: 'Non è un nodo attività', defaultModel: 'Modello predefinito', activity: 'Attività', activityOverview: 'Sessioni attive', activeTasks: 'attività attive', noActiveTasks: 'Nessuna sessione attiva o attività acquisita', approvalTitle: 'Richiesta Provider', response: 'Risposta', allow: 'Consenti', deny: 'Nega', allocated: 'Assegnato', starting: 'Avvio', running: 'In esecuzione', interrupting: 'Interruzione in corso', interrupted: 'Interrotto', completed: 'Completato', cancelled: 'Annullato' },
			cs: { signIn: 'Přihlásit se', createdAt: 'Vytvořeno', nodeId: 'ID uzlu', level: 'Úroveň', childCount: 'Potomci', tags: 'Štítky', taskStatus: 'Stav úkolu', taskLabels: 'Štítky úkolu', sidecarState: 'Stav doprovodných dat', diagnostic: 'Diagnostika', sessionTrace: 'Trasování relace', noSessionRecord: 'Žádný záznam relace', executionState: 'Stav provádění', worker: 'Vykonavatel', leaseUntil: 'Konec pronájmu', failureReason: 'Důvod selhání', claimed: 'Probíhá', done: 'Dokončeno', released: 'Uvolněno', failedState: 'Selhalo', leaseExpired: 'Pronájem vypršel', pending: 'Čeká', kmUnavailable: 'Provádění KM není dostupné', nonTask: 'Není uzel úkolu', defaultModel: 'Výchozí model', activity: 'Aktivita', activityOverview: 'Aktivní relace', activeTasks: 'aktivní úkoly', noActiveTasks: 'Žádné aktivní relace ani rezervované úkoly', approvalTitle: 'Požadavek poskytovatele', response: 'Odpověď', allow: 'Povolit', deny: 'Zamítnout', allocated: 'Přiděleno', starting: 'Spouštění', running: 'Probíhá', interrupting: 'Přerušování', interrupted: 'Přerušeno', completed: 'Dokončeno', cancelled: 'Zrušeno' },
			hu: { signIn: 'Bejelentkezés', createdAt: 'Létrehozva', nodeId: 'Csomópontazonosító', level: 'Szint', childCount: 'Gyermekek', tags: 'Címkék', taskStatus: 'Feladatállapot', taskLabels: 'Feladatcímkék', sidecarState: 'Kísérőállapot', diagnostic: 'Diagnosztika', sessionTrace: 'Munkamenet-követés', noSessionRecord: 'Nincs munkamenetrekord', executionState: 'Végrehajtási állapot', worker: 'Végrehajtó', leaseUntil: 'Bérlet lejárata', failureReason: 'Hiba oka', claimed: 'Fut', done: 'Befejezve', released: 'Feloldva', failedState: 'Sikertelen', leaseExpired: 'Bérlet lejárt', pending: 'Függőben', kmUnavailable: 'A KM-végrehajtás nem érhető el', nonTask: 'Nem feladatcsomópont', defaultModel: 'Alapértelmezett modell', activity: 'Aktivitás', activityOverview: 'Aktív munkamenetek', activeTasks: 'aktív feladat', noActiveTasks: 'Nincs aktív munkamenet vagy lefoglalt feladat', approvalTitle: 'Szolgáltatói kérés', response: 'Válasz', allow: 'Engedélyezés', deny: 'Elutasítás', allocated: 'Hozzárendelve', starting: 'Indítás', running: 'Fut', interrupting: 'Megszakítás', interrupted: 'Megszakítva', completed: 'Befejezve', cancelled: 'Visszavonva' },
			ja: { signIn: 'サインイン', createdAt: '作成日時', nodeId: 'ノード ID', level: '階層', childCount: '子ノード', tags: 'タグ', taskStatus: 'タスク状態', taskLabels: 'タスクラベル', sidecarState: 'サイドカー状態', diagnostic: '診断', sessionTrace: 'セッション追跡', noSessionRecord: 'セッション記録なし', executionState: '実行状態', worker: '実行者', leaseUntil: 'リース期限', failureReason: '失敗理由', claimed: '実行中', done: '完了', released: '解放済み', failedState: '失敗', leaseExpired: 'リース期限切れ', pending: '保留中', kmUnavailable: 'KM 実行を利用できません', nonTask: 'タスクノードではありません', defaultModel: '既定モデル', activity: 'アクティビティ', activityOverview: 'アクティブなセッション', activeTasks: '件のアクティブタスク', noActiveTasks: 'アクティブなセッションまたは取得済みタスクはありません', approvalTitle: 'プロバイダー要求', response: '回答', allow: '許可', deny: '拒否', allocated: '割り当て済み', starting: '起動中', running: '実行中', interrupting: '中断中', interrupted: '中断済み', completed: '完了', cancelled: 'キャンセル済み' },
			ko: { signIn: '로그인', createdAt: '생성됨', nodeId: '노드 ID', level: '수준', childCount: '하위 노드', tags: '태그', taskStatus: '작업 상태', taskLabels: '작업 레이블', sidecarState: '사이드카 상태', diagnostic: '진단', sessionTrace: '세션 추적', noSessionRecord: '세션 기록 없음', executionState: '실행 상태', worker: '실행자', leaseUntil: '임대 만료', failureReason: '실패 이유', claimed: '실행 중', done: '완료됨', released: '해제됨', failedState: '실패', leaseExpired: '임대 만료됨', pending: '대기 중', kmUnavailable: 'KM 실행을 사용할 수 없음', nonTask: '작업 노드가 아님', defaultModel: '기본 모델', activity: '활동', activityOverview: '활성 세션', activeTasks: '개의 활성 작업', noActiveTasks: '활성 세션 또는 할당된 작업이 없습니다', approvalTitle: '제공자 요청', response: '응답', allow: '허용', deny: '거부', allocated: '할당됨', starting: '시작 중', running: '실행 중', interrupting: '중단 중', interrupted: '중단됨', completed: '완료됨', cancelled: '취소됨' },
			pl: { signIn: 'Zaloguj się', createdAt: 'Utworzono', nodeId: 'ID węzła', level: 'Poziom', childCount: 'Elementy podrzędne', tags: 'Tagi', taskStatus: 'Stan zadania', taskLabels: 'Etykiety zadania', sidecarState: 'Stan pomocniczy', diagnostic: 'Diagnostyka', sessionTrace: 'Śledzenie sesji', noSessionRecord: 'Brak rekordu sesji', executionState: 'Stan wykonania', worker: 'Wykonawca', leaseUntil: 'Koniec dzierżawy', failureReason: 'Przyczyna błędu', claimed: 'Uruchomione', done: 'Ukończono', released: 'Zwolniono', failedState: 'Niepowodzenie', leaseExpired: 'Dzierżawa wygasła', pending: 'Oczekuje', kmUnavailable: 'Wykonanie KM niedostępne', nonTask: 'To nie jest węzeł zadania', defaultModel: 'Model domyślny', activity: 'Aktywność', activityOverview: 'Aktywne sesje', activeTasks: 'aktywne zadania', noActiveTasks: 'Brak aktywnych sesji i zajętych zadań', approvalTitle: 'Żądanie dostawcy', response: 'Odpowiedź', allow: 'Zezwól', deny: 'Odmów', allocated: 'Przypisano', starting: 'Uruchamianie', running: 'Uruchomione', interrupting: 'Przerywanie', interrupted: 'Przerwano', completed: 'Ukończono', cancelled: 'Anulowano' },
			pt: { signIn: 'Iniciar sessão', createdAt: 'Criado', nodeId: 'ID do nó', level: 'Nível', childCount: 'Filhos', tags: 'Etiquetas', taskStatus: 'Estado da tarefa', taskLabels: 'Etiquetas da tarefa', sidecarState: 'Estado auxiliar', diagnostic: 'Diagnóstico', sessionTrace: 'Rastreio da sessão', noSessionRecord: 'Sem registo de sessão', executionState: 'Estado da execução', worker: 'Executor', leaseUntil: 'Fim da concessão', failureReason: 'Motivo da falha', claimed: 'Em execução', done: 'Concluído', released: 'Libertado', failedState: 'Falhou', leaseExpired: 'Concessão expirada', pending: 'Pendente', kmUnavailable: 'Execução KM indisponível', nonTask: 'Não é um nó de tarefa', defaultModel: 'Modelo predefinido', activity: 'Atividade', activityOverview: 'Sessões ativas', activeTasks: 'tarefas ativas', noActiveTasks: 'Sem sessões ativas ou tarefas reservadas', approvalTitle: 'Pedido do fornecedor', response: 'Resposta', allow: 'Permitir', deny: 'Recusar', allocated: 'Alocado', starting: 'A iniciar', running: 'Em execução', interrupting: 'A interromper', interrupted: 'Interrompido', completed: 'Concluído', cancelled: 'Cancelado' },
			ru: { signIn: 'Войти', createdAt: 'Создано', nodeId: 'ID узла', level: 'Уровень', childCount: 'Дочерние узлы', tags: 'Теги', taskStatus: 'Состояние задачи', taskLabels: 'Метки задачи', sidecarState: 'Состояние sidecar', diagnostic: 'Диагностика', sessionTrace: 'Трассировка сеанса', noSessionRecord: 'Нет записи сеанса', executionState: 'Состояние выполнения', worker: 'Исполнитель', leaseUntil: 'Срок аренды', failureReason: 'Причина ошибки', claimed: 'Выполняется', done: 'Завершено', released: 'Освобождено', failedState: 'Ошибка', leaseExpired: 'Аренда истекла', pending: 'Ожидает', kmUnavailable: 'Выполнение KM недоступно', nonTask: 'Не является узлом задачи', defaultModel: 'Модель по умолчанию', activity: 'Активность', activityOverview: 'Активные сеансы', activeTasks: 'активных задач', noActiveTasks: 'Нет активных сеансов или занятых задач', approvalTitle: 'Запрос провайдера', response: 'Ответ', allow: 'Разрешить', deny: 'Отклонить', allocated: 'Назначено', starting: 'Запускается', running: 'Выполняется', interrupting: 'Прерывается', interrupted: 'Прервано', completed: 'Завершено', cancelled: 'Отменено' },
			no: { signIn: 'Logg på', createdAt: 'Opprettet', nodeId: 'Node-ID', level: 'Nivå', childCount: 'Barn', tags: 'Etiketter', taskStatus: 'Oppgavestatus', taskLabels: 'Oppgaveetiketter', sidecarState: 'Sidestatus', diagnostic: 'Diagnostikk', sessionTrace: 'Øktsporing', noSessionRecord: 'Ingen øktoppføring', executionState: 'Kjørestatus', worker: 'Utfører', leaseUntil: 'Leie utløper', failureReason: 'Feilårsak', claimed: 'Kjører', done: 'Fullført', released: 'Frigitt', failedState: 'Mislyktes', leaseExpired: 'Leie utløpt', pending: 'Venter', kmUnavailable: 'KM-kjøring utilgjengelig', nonTask: 'Ikke en oppgavenode', defaultModel: 'Standardmodell', activity: 'Aktivitet', activityOverview: 'Aktive økter', activeTasks: 'aktive oppgaver', noActiveTasks: 'Ingen aktive økter eller reserverte oppgaver', approvalTitle: 'Leverandørforespørsel', response: 'Svar', allow: 'Tillat', deny: 'Avslå', allocated: 'Tildelt', starting: 'Starter', running: 'Kjører', interrupting: 'Avbryter', interrupted: 'Avbrutt', completed: 'Fullført', cancelled: 'Kansellert' },
			br: { signIn: 'Entrar', createdAt: 'Criado', nodeId: 'ID do nó', level: 'Nível', childCount: 'Filhos', tags: 'Etiquetas', taskStatus: 'Status da tarefa', taskLabels: 'Etiquetas da tarefa', sidecarState: 'Status auxiliar', diagnostic: 'Diagnóstico', sessionTrace: 'Rastreamento da sessão', noSessionRecord: 'Sem registro de sessão', executionState: 'Status da execução', worker: 'Executor', leaseUntil: 'Fim da concessão', failureReason: 'Motivo da falha', claimed: 'Em execução', done: 'Concluído', released: 'Liberado', failedState: 'Falhou', leaseExpired: 'Concessão expirada', pending: 'Pendente', kmUnavailable: 'Execução KM indisponível', nonTask: 'Não é um nó de tarefa', defaultModel: 'Modelo padrão', activity: 'Atividade', activityOverview: 'Sessões ativas', activeTasks: 'tarefas ativas', noActiveTasks: 'Sem sessões ativas ou tarefas reservadas', approvalTitle: 'Solicitação do provedor', response: 'Resposta', allow: 'Permitir', deny: 'Negar', allocated: 'Alocado', starting: 'Iniciando', running: 'Em execução', interrupting: 'Interrompendo', interrupted: 'Interrompido', completed: 'Concluído', cancelled: 'Cancelado' },
			th: { signIn: 'เข้าสู่ระบบ', createdAt: 'สร้างเมื่อ', nodeId: 'ID โหนด', level: 'ระดับ', childCount: 'โหนดย่อย', tags: 'แท็ก', taskStatus: 'สถานะงาน', taskLabels: 'ป้ายกำกับงาน', sidecarState: 'สถานะไซด์คาร์', diagnostic: 'การวินิจฉัย', sessionTrace: 'การติดตามเซสชัน', noSessionRecord: 'ไม่มีบันทึกเซสชัน', executionState: 'สถานะการทำงาน', worker: 'ผู้ดำเนินการ', leaseUntil: 'สิ้นสุดสัญญาเช่า', failureReason: 'สาเหตุที่ล้มเหลว', claimed: 'กำลังทำงาน', done: 'เสร็จสิ้น', released: 'ปล่อยแล้ว', failedState: 'ล้มเหลว', leaseExpired: 'สัญญาเช่าหมดอายุ', pending: 'รอดำเนินการ', kmUnavailable: 'ใช้การทำงาน KM ไม่ได้', nonTask: 'ไม่ใช่โหนดงาน', defaultModel: 'โมเดลเริ่มต้น', activity: 'กิจกรรม', activityOverview: 'เซสชันที่ใช้งานอยู่', activeTasks: 'งานที่ใช้งานอยู่', noActiveTasks: 'ไม่มีเซสชันที่ใช้งานหรืองานที่รับไว้', approvalTitle: 'คำขอจากผู้ให้บริการ', response: 'คำตอบ', allow: 'อนุญาต', deny: 'ปฏิเสธ', allocated: 'จัดสรรแล้ว', starting: 'กำลังเริ่ม', running: 'กำลังทำงาน', interrupting: 'กำลังหยุด', interrupted: 'หยุดแล้ว', completed: 'เสร็จสิ้น', cancelled: 'ยกเลิกแล้ว' },
			da: { signIn: 'Log ind', createdAt: 'Oprettet', nodeId: 'Node-id', level: 'Niveau', childCount: 'Undernoder', tags: 'Mærker', taskStatus: 'Opgavestatus', taskLabels: 'Opgavemærker', sidecarState: 'Sidestatus', diagnostic: 'Diagnostik', sessionTrace: 'Sessionssporing', noSessionRecord: 'Ingen sessionspost', executionState: 'Kørselsstatus', worker: 'Udfører', leaseUntil: 'Leje udløber', failureReason: 'Fejlårsag', claimed: 'Kører', done: 'Fuldført', released: 'Frigivet', failedState: 'Mislykket', leaseExpired: 'Leje udløbet', pending: 'Afventer', kmUnavailable: 'KM-kørsel utilgængelig', nonTask: 'Ikke en opgavenode', defaultModel: 'Standardmodel', activity: 'Aktivitet', activityOverview: 'Aktive sessioner', activeTasks: 'aktive opgaver', noActiveTasks: 'Ingen aktive sessioner eller reserverede opgaver', approvalTitle: 'Udbyderanmodning', response: 'Svar', allow: 'Tillad', deny: 'Afvis', allocated: 'Tildelt', starting: 'Starter', running: 'Kører', interrupting: 'Afbryder', interrupted: 'Afbrudt', completed: 'Fuldført', cancelled: 'Annulleret' },
			bs: { signIn: 'Prijavi se', createdAt: 'Kreirano', nodeId: 'ID čvora', level: 'Nivo', childCount: 'Podčvorovi', tags: 'Oznake', taskStatus: 'Status zadatka', taskLabels: 'Oznake zadatka', sidecarState: 'Pomoćni status', diagnostic: 'Dijagnostika', sessionTrace: 'Praćenje sesije', noSessionRecord: 'Nema zapisa sesije', executionState: 'Status izvršenja', worker: 'Izvršilac', leaseUntil: 'Istek zakupa', failureReason: 'Razlog neuspjeha', claimed: 'Pokrenuto', done: 'Završeno', released: 'Oslobođeno', failedState: 'Neuspjelo', leaseExpired: 'Zakup istekao', pending: 'Na čekanju', kmUnavailable: 'KM izvršavanje nije dostupno', nonTask: 'Nije čvor zadatka', defaultModel: 'Zadani model', activity: 'Aktivnost', activityOverview: 'Aktivne sesije', activeTasks: 'aktivni zadaci', noActiveTasks: 'Nema aktivnih sesija ni zauzetih zadataka', approvalTitle: 'Zahtjev pružaoca', response: 'Odgovor', allow: 'Dozvoli', deny: 'Odbij', allocated: 'Dodijeljeno', starting: 'Pokretanje', running: 'Pokrenuto', interrupting: 'Prekidanje', interrupted: 'Prekinuto', completed: 'Završeno', cancelled: 'Otkazano' },
			tr: { signIn: 'Oturum aç', createdAt: 'Oluşturuldu', nodeId: 'Düğüm kimliği', level: 'Düzey', childCount: 'Alt düğümler', tags: 'Etiketler', taskStatus: 'Görev durumu', taskLabels: 'Görev etiketleri', sidecarState: 'Yardımcı durum', diagnostic: 'Tanılama', sessionTrace: 'Oturum izleme', noSessionRecord: 'Oturum kaydı yok', executionState: 'Yürütme durumu', worker: 'Yürütücü', leaseUntil: 'Kira bitişi', failureReason: 'Hata nedeni', claimed: 'Çalışıyor', done: 'Tamamlandı', released: 'Serbest bırakıldı', failedState: 'Başarısız', leaseExpired: 'Kira süresi doldu', pending: 'Bekliyor', kmUnavailable: 'KM yürütmesi kullanılamıyor', nonTask: 'Görev düğümü değil', defaultModel: 'Varsayılan model', activity: 'Etkinlik', activityOverview: 'Etkin oturumlar', activeTasks: 'etkin görevler', noActiveTasks: 'Etkin oturum veya alınmış görev yok', approvalTitle: 'Sağlayıcı isteği', response: 'Yanıt', allow: 'İzin ver', deny: 'Reddet', allocated: 'Atandı', starting: 'Başlatılıyor', running: 'Çalışıyor', interrupting: 'Durduruluyor', interrupted: 'Durduruldu', completed: 'Tamamlandı', cancelled: 'İptal edildi' },
			ar: { signIn: 'تسجيل الدخول', createdAt: 'تاريخ الإنشاء', nodeId: 'معرّف العقدة', level: 'المستوى', childCount: 'العقد الفرعية', tags: 'الوسوم', taskStatus: 'حالة المهمة', taskLabels: 'وسوم المهمة', sidecarState: 'حالة الملف الجانبي', diagnostic: 'التشخيص', sessionTrace: 'تتبّع الجلسة', noSessionRecord: 'لا يوجد سجل جلسة', executionState: 'حالة التنفيذ', worker: 'المنفّذ', leaseUntil: 'انتهاء الإيجار', failureReason: 'سبب الفشل', claimed: 'قيد التشغيل', done: 'مكتمل', released: 'تم التحرير', failedState: 'فشل', leaseExpired: 'انتهى الإيجار', pending: 'قيد الانتظار', kmUnavailable: 'تنفيذ KM غير متاح', nonTask: 'ليست عقدة مهمة', defaultModel: 'النموذج الافتراضي', activity: 'النشاط', activityOverview: 'الجلسات النشطة', activeTasks: 'مهام نشطة', noActiveTasks: 'لا توجد جلسات نشطة أو مهام محجوزة', approvalTitle: 'طلب المزوّد', response: 'الرد', allow: 'سماح', deny: 'رفض', allocated: 'مُعيَّن', starting: 'جارٍ البدء', running: 'قيد التشغيل', interrupting: 'جارٍ المقاطعة', interrupted: 'مُقاطَع', completed: 'مكتمل', cancelled: 'ملغى' },
			'zh-cn': { approvalTitle: '提供方请求', response: '回复', allow: '允许', deny: '拒绝', allocated: '已分配', starting: '启动中', running: '运行中', interrupting: '中止中', interrupted: '已中止', completed: '已完成', cancelled: '已取消' },
			'zh-tw': { approvalTitle: '提供方要求', response: '回覆', allow: '允許', deny: '拒絕', activity: '活動', activityOverview: '活動工作階段', activeTasks: '個活動任務', noActiveTasks: '目前沒有活動工作階段或已認領任務', allocated: '已分配', starting: '啟動中', running: '執行中', interrupting: '中止中', interrupted: '已中止', completed: '已完成', cancelled: '已取消' }
		};
		var dictionaries = {
			en: en,
			de: Object.assign({}, en, { provider: 'Anbieter', model: 'Modell', effort: 'Aufwand', defaultEffort: 'Standard', instruction: 'Zusätzliche Anweisung', instructionPlaceholder: 'Optionale Anweisung hinzufügen', send: 'Senden', append: 'Anhängen', interrupt: 'Unterbrechen', install: 'Installieren', cancel: 'Abbrechen', installTitle: 'Anbieter installieren', close: 'Schließen', history: 'Sitzungsverlauf', records: 'Einträge', loading: 'Wird geladen…', noSessions: 'Noch keine Sitzungen', orphan: 'Der ursprüngliche Knoten fehlt; der Verlauf bleibt erhalten.', requested: 'Angefordert', effective: 'Wirksam', artifacts: 'Artefakte', copySessionId: 'Sitzungs-ID kopieren', loadMore: 'Mehr laden', missing: 'Fehlt', installed_inactive: 'Installiert', ready: 'Bereit', auth_required: 'Anmeldung erforderlich', degraded: 'Eingeschränkt', incompatible: 'Inkompatibel', failed: 'Fehlgeschlagen', loadingState: 'Wird geladen', unavailable: 'Nicht verfügbar', dirty: 'Mindmap vor dem Senden speichern.', active: 'Wird ausgeführt', idle: 'Inaktiv', error: 'Sitzungsfehler', copyDone: 'Kopiert' }),
			es: Object.assign({}, en, { provider: 'Proveedor', model: 'Modelo', effort: 'Esfuerzo', defaultEffort: 'Predeterminado', instruction: 'Instrucción adicional', instructionPlaceholder: 'Añadir una instrucción opcional', send: 'Enviar', append: 'Añadir', interrupt: 'Interrumpir', install: 'Instalar', cancel: 'Cancelar', installTitle: 'Instalar proveedor', close: 'Cerrar', history: 'Historial de sesiones', records: 'registros', loading: 'Cargando…', noSessions: 'Aún no hay sesiones', orphan: 'El nodo original ya no existe; se conserva el historial.', requested: 'Solicitado', effective: 'Efectivo', artifacts: 'Artefactos', copySessionId: 'Copiar ID de sesión', loadMore: 'Cargar más', missing: 'Falta', installed_inactive: 'Instalado', ready: 'Listo', auth_required: 'Inicio de sesión requerido', degraded: 'Degradado', incompatible: 'Incompatible', failed: 'Fallido', loadingState: 'Cargando', unavailable: 'No disponible', dirty: 'Guarda el mapa mental antes de enviar.', active: 'En ejecución', idle: 'Inactivo', error: 'Error de sesión', copyDone: 'Copiado' }),
			fr: Object.assign({}, en, { provider: 'Fournisseur', model: 'Modèle', effort: 'Effort', defaultEffort: 'Par défaut', instruction: 'Instruction supplémentaire', instructionPlaceholder: 'Ajouter une instruction facultative', send: 'Envoyer', append: 'Ajouter', interrupt: 'Interrompre', install: 'Installer', cancel: 'Annuler', installTitle: 'Installer le fournisseur', close: 'Fermer', history: 'Historique des sessions', records: 'éléments', loading: 'Chargement…', noSessions: 'Aucune session', orphan: 'Le nœud d’origine a disparu ; l’historique est conservé.', requested: 'Demandé', effective: 'Effectif', artifacts: 'Artefacts', copySessionId: 'Copier l’ID de session', loadMore: 'Charger plus', missing: 'Absent', installed_inactive: 'Installé', ready: 'Prêt', auth_required: 'Connexion requise', degraded: 'Dégradé', incompatible: 'Incompatible', failed: 'Échec', loadingState: 'Chargement', unavailable: 'Indisponible', dirty: 'Enregistrez la carte avant l’envoi.', active: 'En cours', idle: 'Inactif', error: 'Erreur de session', copyDone: 'Copié' }),
			it: Object.assign({}, en, { provider: 'Provider', model: 'Modello', effort: 'Impegno', defaultEffort: 'Predefinito', instruction: 'Istruzione aggiuntiva', instructionPlaceholder: 'Aggiungi un’istruzione facoltativa', send: 'Invia', append: 'Aggiungi', interrupt: 'Interrompi', install: 'Installa', cancel: 'Annulla', installTitle: 'Installa Provider', close: 'Chiudi', history: 'Cronologia sessioni', records: 'record', loading: 'Caricamento…', noSessions: 'Nessuna sessione', orphan: 'Il nodo originale non esiste più; la cronologia è conservata.', requested: 'Richiesto', effective: 'Effettivo', artifacts: 'Artefatti', copySessionId: 'Copia ID sessione', loadMore: 'Carica altro', missing: 'Mancante', installed_inactive: 'Installato', ready: 'Pronto', auth_required: 'Accesso richiesto', degraded: 'Degradato', incompatible: 'Incompatibile', failed: 'Non riuscito', loadingState: 'Caricamento', unavailable: 'Non disponibile', dirty: 'Salva la mappa prima dell’invio.', active: 'In esecuzione', idle: 'Inattivo', error: 'Errore sessione', copyDone: 'Copiato' }),
			cs: Object.assign({}, en, { provider: 'Poskytovatel', model: 'Model', effort: 'Úsilí', defaultEffort: 'Výchozí', instruction: 'Doplňující pokyn', instructionPlaceholder: 'Přidat volitelný pokyn', send: 'Odeslat', append: 'Přidat', interrupt: 'Přerušit', install: 'Nainstalovat', cancel: 'Zrušit', installTitle: 'Instalovat poskytovatele', close: 'Zavřít', history: 'Historie relací', records: 'záznamů', loading: 'Načítání…', noSessions: 'Zatím žádné relace', orphan: 'Původní uzel chybí; historie je zachována.', requested: 'Požadováno', effective: 'Skutečné', artifacts: 'Artefakty', copySessionId: 'Kopírovat ID relace', loadMore: 'Načíst další', missing: 'Chybí', installed_inactive: 'Nainstalováno', ready: 'Připraveno', auth_required: 'Vyžadováno přihlášení', degraded: 'Omezené', incompatible: 'Nekompatibilní', failed: 'Selhalo', loadingState: 'Načítání', unavailable: 'Nedostupné', dirty: 'Před odesláním mapu uložte.', active: 'Probíhá', idle: 'Nečinné', error: 'Chyba relace', copyDone: 'Zkopírováno' }),
			hu: Object.assign({}, en, { provider: 'Szolgáltató', model: 'Modell', effort: 'Erőfeszítés', defaultEffort: 'Alapértelmezett', instruction: 'További utasítás', instructionPlaceholder: 'Opcionális utasítás hozzáadása', send: 'Küldés', append: 'Hozzáadás', interrupt: 'Megszakítás', install: 'Telepítés', cancel: 'Mégse', installTitle: 'Szolgáltató telepítése', close: 'Bezárás', history: 'Munkamenet-előzmények', records: 'bejegyzés', loading: 'Betöltés…', noSessions: 'Még nincs munkamenet', orphan: 'Az eredeti csomópont már nincs meg; az előzmény megmarad.', requested: 'Kért', effective: 'Tényleges', artifacts: 'Eredmények', copySessionId: 'Munkamenet-azonosító másolása', loadMore: 'Továbbiak', missing: 'Hiányzik', installed_inactive: 'Telepítve', ready: 'Kész', auth_required: 'Bejelentkezés szükséges', degraded: 'Korlátozott', incompatible: 'Nem kompatibilis', failed: 'Sikertelen', loadingState: 'Betöltés', unavailable: 'Nem érhető el', dirty: 'Küldés előtt mentse a térképet.', active: 'Fut', idle: 'Tétlen', error: 'Munkamenethiba', copyDone: 'Másolva' }),
			ja: Object.assign({}, en, { provider: 'プロバイダー', model: 'モデル', effort: '推論レベル', defaultEffort: '既定', instruction: '追加指示', instructionPlaceholder: '任意の追加指示', send: '送信', append: '追加送信', interrupt: '中断', install: 'インストール', cancel: 'キャンセル', installTitle: 'プロバイダーをインストール', close: '閉じる', history: 'セッション履歴', records: '件', loading: '読み込み中…', noSessions: 'セッションはまだありません', orphan: '元のノードは存在しませんが、履歴は保持されています。', requested: '要求値', effective: '実効値', artifacts: '成果物', copySessionId: 'セッション ID をコピー', loadMore: 'さらに読み込む', missing: '未導入', installed_inactive: 'インストール済み', ready: '準備完了', auth_required: 'サインインが必要', degraded: '制限あり', incompatible: '非互換', failed: '失敗', loadingState: '読み込み中', unavailable: '利用不可', dirty: '送信前にマインドマップを保存してください。', active: '実行中', idle: '待機中', error: 'セッションエラー', copyDone: 'コピーしました' }),
			ko: Object.assign({}, en, { provider: '제공자', model: '모델', effort: '추론 수준', defaultEffort: '기본값', instruction: '추가 지침', instructionPlaceholder: '선택 지침 추가', send: '보내기', append: '추가 전송', interrupt: '중단', install: '설치', cancel: '취소', installTitle: '제공자 설치', close: '닫기', history: '세션 기록', records: '개', loading: '불러오는 중…', noSessions: '아직 세션이 없습니다', orphan: '원래 노드는 없지만 기록은 보존됩니다.', requested: '요청값', effective: '적용값', artifacts: '결과물', copySessionId: '세션 ID 복사', loadMore: '더 불러오기', missing: '없음', installed_inactive: '설치됨', ready: '준비됨', auth_required: '로그인 필요', degraded: '제한됨', incompatible: '호환되지 않음', failed: '실패', loadingState: '불러오는 중', unavailable: '사용 불가', dirty: '보내기 전에 마인드맵을 저장하세요.', active: '실행 중', idle: '대기 중', error: '세션 오류', copyDone: '복사됨' }),
			pl: Object.assign({}, en, { provider: 'Dostawca', model: 'Model', effort: 'Wysiłek', defaultEffort: 'Domyślne', instruction: 'Dodatkowa instrukcja', instructionPlaceholder: 'Dodaj opcjonalną instrukcję', send: 'Wyślij', append: 'Dołącz', interrupt: 'Przerwij', install: 'Zainstaluj', cancel: 'Anuluj', installTitle: 'Zainstaluj dostawcę', close: 'Zamknij', history: 'Historia sesji', records: 'rekordów', loading: 'Ładowanie…', noSessions: 'Brak sesji', orphan: 'Pierwotny węzeł nie istnieje; historia została zachowana.', requested: 'Żądane', effective: 'Efektywne', artifacts: 'Artefakty', copySessionId: 'Kopiuj ID sesji', loadMore: 'Wczytaj więcej', missing: 'Brak', installed_inactive: 'Zainstalowano', ready: 'Gotowe', auth_required: 'Wymagane logowanie', degraded: 'Ograniczone', incompatible: 'Niezgodne', failed: 'Niepowodzenie', loadingState: 'Ładowanie', unavailable: 'Niedostępne', dirty: 'Zapisz mapę przed wysłaniem.', active: 'Uruchomione', idle: 'Bezczynne', error: 'Błąd sesji', copyDone: 'Skopiowano' }),
			pt: Object.assign({}, en, { provider: 'Fornecedor', model: 'Modelo', effort: 'Esforço', defaultEffort: 'Predefinido', instruction: 'Instrução adicional', instructionPlaceholder: 'Adicionar uma instrução opcional', send: 'Enviar', append: 'Adicionar', interrupt: 'Interromper', install: 'Instalar', cancel: 'Cancelar', installTitle: 'Instalar fornecedor', close: 'Fechar', history: 'Histórico de sessões', records: 'registos', loading: 'A carregar…', noSessions: 'Ainda não há sessões', orphan: 'O nó original já não existe; o histórico foi preservado.', requested: 'Pedido', effective: 'Efetivo', artifacts: 'Artefactos', copySessionId: 'Copiar ID da sessão', loadMore: 'Carregar mais', missing: 'Em falta', installed_inactive: 'Instalado', ready: 'Pronto', auth_required: 'Início de sessão necessário', degraded: 'Limitado', incompatible: 'Incompatível', failed: 'Falhou', loadingState: 'A carregar', unavailable: 'Indisponível', dirty: 'Guarde o mapa antes de enviar.', active: 'Em execução', idle: 'Inativo', error: 'Erro de sessão', copyDone: 'Copiado' }),
			ru: Object.assign({}, en, { provider: 'Провайдер', model: 'Модель', effort: 'Уровень рассуждения', defaultEffort: 'По умолчанию', instruction: 'Дополнительная инструкция', instructionPlaceholder: 'Добавьте необязательную инструкцию', send: 'Отправить', append: 'Дополнить', interrupt: 'Прервать', install: 'Установить', cancel: 'Отмена', installTitle: 'Установить провайдер', close: 'Закрыть', history: 'История сеансов', records: 'записей', loading: 'Загрузка…', noSessions: 'Сеансов пока нет', orphan: 'Исходный узел удалён; история сохранена.', requested: 'Запрошено', effective: 'Фактически', artifacts: 'Артефакты', copySessionId: 'Копировать ID сеанса', loadMore: 'Загрузить ещё', missing: 'Отсутствует', installed_inactive: 'Установлен', ready: 'Готов', auth_required: 'Требуется вход', degraded: 'Ограничен', incompatible: 'Несовместим', failed: 'Ошибка', loadingState: 'Загрузка', unavailable: 'Недоступен', dirty: 'Сохраните карту перед отправкой.', active: 'Выполняется', idle: 'Ожидание', error: 'Ошибка сеанса', copyDone: 'Скопировано' }),
			'zh-cn': Object.assign({}, en, { provider: '提供方', switchProvider: '切换提供方', collapseControlBar: '收起智能体控制条', expandControlBar: '展开智能体控制条', model: '模型', effort: '推理强度', defaultEffort: '默认', signIn: '登录', instruction: '后续变更要求', instructionPlaceholder: '提出后续变更要求', send: '发送', sending: '发送中…', append: '追加发送', interrupt: '中止', install: '安装', cancel: '取消', installTitle: '安装提供方', close: '关闭', history: '会话历史', records: '条记录', loading: '正在读取…', noSessions: '尚无会话', orphan: '原节点已不存在，历史记录仍保留。', requested: '请求配置', effective: '实际配置', artifacts: '产物', copySessionId: '复制会话 ID', loadMore: '加载更多', missing: '未安装', installed_inactive: '已安装', ready: '就绪', auth_required: '需要登录', degraded: '能力受限', incompatible: '不兼容', failed: '失败', loadingState: '正在加载', unavailable: '不可用', dirty: '请先保存当前思维导图。', active: '运行中', idle: '空闲', error: '错误', dismiss: '×', copyDone: '已复制', createdAt: '创建时间', nodeId: '节点 ID', level: '层级', childCount: '子节点数', tags: '标签', taskStatus: '任务状态', taskLabels: '任务标签', sidecarState: '旁车状态', diagnostic: '诊断', sessionTrace: '会话追溯', noSessionRecord: '尚无会话记录', executionState: '执行状态', worker: '认领人', leaseUntil: '租约到期', failureReason: '失败原因', claimed: '执行中', done: '已完成', released: '已释放', failedState: '已失败', leaseExpired: '租约过期', pending: '待处理', kmUnavailable: 'KM 执行不可用', nonTask: '非任务节点', defaultModel: '默认模型', activity: '活动', activityOverview: '活动会话', activeTasks: '个活动任务', activeSessionsCount: '个活动会话', noActiveTasks: '暂无活动智能体会话', sessionDetail: '会话详情', backToSessions: '返回列表', updatedAt: '更新时间', executionId: '执行 ID', realtimeEvents: '实时会话内容', liveUpdating: '实时更新', noRealtimeEvents: '暂无实时会话内容', approvalTitle: '提供方请求', response: '回复', allow: '允许', deny: '拒绝', allocated: '已分配', starting: '启动中', running: '运行中', interrupting: '中止中', interrupted: '已中止', completed: '已完成', cancelled: '已取消', requestTimedOut: '请求超时。可安全重试，系统会防止重复提交。', toolPermissions: '工具权限', elevatedRisk: '高权限', confirm: '确认', permissionConfirmTitle: '确认高权限模式', permissionConfirmMessage: '此模式会扩大工具访问范围，请确认后应用到下一轮会话。' }),
			'zh-tw': Object.assign({}, en, { provider: '提供方', switchProvider: '切換提供方', collapseControlBar: '收合智慧體控制列', expandControlBar: '展開智慧體控制列', model: '模型', effort: '推理強度', defaultEffort: '預設', signIn: '登入', instruction: '後續變更要求', instructionPlaceholder: '提出後續變更要求', send: '傳送', append: '追加傳送', interrupt: '中止', install: '安裝', cancel: '取消', installTitle: '安裝提供方', close: '關閉', history: '工作階段歷程', records: '筆記錄', loading: '正在讀取…', noSessions: '尚無工作階段', orphan: '原節點已不存在，歷程仍保留。', requested: '要求設定', effective: '實際設定', artifacts: '產出', copySessionId: '複製工作階段 ID', loadMore: '載入更多', missing: '未安裝', installed_inactive: '已安裝', ready: '就緒', auth_required: '需要登入', degraded: '功能受限', incompatible: '不相容', failed: '失敗', loadingState: '正在載入', unavailable: '無法使用', dirty: '請先儲存目前心智圖。', active: '執行中', idle: '閒置', error: '工作階段錯誤', copyDone: '已複製', createdAt: '建立時間', nodeId: '節點 ID', level: '層級', childCount: '子節點數', tags: '標籤', taskStatus: '任務狀態', taskLabels: '任務標籤', sidecarState: '旁車狀態', diagnostic: '診斷', sessionTrace: '工作階段追溯', noSessionRecord: '尚無工作階段記錄', executionState: '執行狀態', worker: '認領者', leaseUntil: '租約到期', failureReason: '失敗原因', claimed: '執行中', done: '已完成', released: '已釋放', failedState: '已失敗', leaseExpired: '租約過期', pending: '待處理', kmUnavailable: 'KM 執行無法使用', nonTask: '非任務節點', defaultModel: '預設模型', activity: '活動', activityOverview: '活動工作階段', activeTasks: '個活動任務', activeSessionsCount: '個活動工作階段', noActiveTasks: '目前沒有活動智慧體工作階段', sessionDetail: '工作階段詳情', backToSessions: '返回列表', updatedAt: '更新時間', executionId: '執行 ID', realtimeEvents: '即時工作階段內容', liveUpdating: '即時更新', noRealtimeEvents: '尚無即時工作階段內容', allocated: '已分配', starting: '啟動中', running: '執行中', interrupting: '中止中', interrupted: '已中止', completed: '已完成', cancelled: '已取消' }),
			no: Object.assign({}, en, { provider: 'Leverandør', model: 'Modell', effort: 'Innsats', defaultEffort: 'Standard', instruction: 'Tilleggsinstruksjon', instructionPlaceholder: 'Legg til en valgfri instruksjon', send: 'Send', append: 'Legg til', interrupt: 'Avbryt', install: 'Installer', cancel: 'Avbryt', installTitle: 'Installer leverandør', close: 'Lukk', history: 'Økthistorikk', records: 'oppføringer', loading: 'Laster…', noSessions: 'Ingen økter ennå', orphan: 'Den opprinnelige noden er borte; historikken er bevart.', requested: 'Forespurt', effective: 'Gjeldende', artifacts: 'Resultater', copySessionId: 'Kopier økt-ID', loadMore: 'Last inn mer', missing: 'Mangler', installed_inactive: 'Installert', ready: 'Klar', auth_required: 'Pålogging kreves', degraded: 'Begrenset', incompatible: 'Ikke kompatibel', failed: 'Mislyktes', loadingState: 'Laster', unavailable: 'Utilgjengelig', dirty: 'Lagre tankekartet før du sender.', active: 'Kjører', idle: 'Inaktiv', error: 'Øktfeil', copyDone: 'Kopiert' }),
			br: Object.assign({}, en, { provider: 'Provedor', model: 'Modelo', effort: 'Esforço', defaultEffort: 'Padrão', instruction: 'Instrução adicional', instructionPlaceholder: 'Adicione uma instrução opcional', send: 'Enviar', append: 'Acrescentar', interrupt: 'Interromper', install: 'Instalar', cancel: 'Cancelar', installTitle: 'Instalar provedor', close: 'Fechar', history: 'Histórico de sessões', records: 'registros', loading: 'Carregando…', noSessions: 'Ainda não há sessões', orphan: 'O nó original não existe mais; o histórico foi preservado.', requested: 'Solicitado', effective: 'Efetivo', artifacts: 'Artefatos', copySessionId: 'Copiar ID da sessão', loadMore: 'Carregar mais', missing: 'Ausente', installed_inactive: 'Instalado', ready: 'Pronto', auth_required: 'Login necessário', degraded: 'Limitado', incompatible: 'Incompatível', failed: 'Falhou', loadingState: 'Carregando', unavailable: 'Indisponível', dirty: 'Salve o mapa mental antes de enviar.', active: 'Em execução', idle: 'Ocioso', error: 'Erro de sessão', copyDone: 'Copiado' }),
			th: Object.assign({}, en, { provider: 'ผู้ให้บริการ', model: 'โมเดล', effort: 'ระดับการคิด', defaultEffort: 'ค่าเริ่มต้น', instruction: 'คำสั่งเพิ่มเติม', instructionPlaceholder: 'เพิ่มคำสั่งเสริมได้', send: 'ส่ง', append: 'ส่งเพิ่ม', interrupt: 'หยุด', install: 'ติดตั้ง', cancel: 'ยกเลิก', installTitle: 'ติดตั้งผู้ให้บริการ', close: 'ปิด', history: 'ประวัติเซสชัน', records: 'รายการ', loading: 'กำลังโหลด…', noSessions: 'ยังไม่มีเซสชัน', orphan: 'โหนดเดิมไม่มีอยู่แล้ว แต่ยังเก็บประวัติไว้', requested: 'ค่าที่ขอ', effective: 'ค่าที่ใช้', artifacts: 'ผลลัพธ์', copySessionId: 'คัดลอก ID เซสชัน', loadMore: 'โหลดเพิ่ม', missing: 'ยังไม่ติดตั้ง', installed_inactive: 'ติดตั้งแล้ว', ready: 'พร้อม', auth_required: 'ต้องเข้าสู่ระบบ', degraded: 'จำกัด', incompatible: 'ไม่รองรับ', failed: 'ล้มเหลว', loadingState: 'กำลังโหลด', unavailable: 'ใช้ไม่ได้', dirty: 'บันทึกแผนผังก่อนส่ง', active: 'กำลังทำงาน', idle: 'ว่าง', error: 'ข้อผิดพลาดเซสชัน', copyDone: 'คัดลอกแล้ว' }),
			da: Object.assign({}, en, { provider: 'Udbyder', model: 'Model', effort: 'Indsats', defaultEffort: 'Standard', instruction: 'Ekstra instruktion', instructionPlaceholder: 'Tilføj en valgfri instruktion', send: 'Send', append: 'Tilføj', interrupt: 'Afbryd', install: 'Installer', cancel: 'Annuller', installTitle: 'Installer udbyder', close: 'Luk', history: 'Sessionshistorik', records: 'poster', loading: 'Indlæser…', noSessions: 'Ingen sessioner endnu', orphan: 'Den oprindelige node mangler; historikken er bevaret.', requested: 'Anmodet', effective: 'Gældende', artifacts: 'Resultater', copySessionId: 'Kopiér sessions-ID', loadMore: 'Indlæs flere', missing: 'Mangler', installed_inactive: 'Installeret', ready: 'Klar', auth_required: 'Login kræves', degraded: 'Begrænset', incompatible: 'Inkompatibel', failed: 'Mislykkedes', loadingState: 'Indlæser', unavailable: 'Utilgængelig', dirty: 'Gem mindmappet før afsendelse.', active: 'Kører', idle: 'Inaktiv', error: 'Sessionsfejl', copyDone: 'Kopieret' }),
			bs: Object.assign({}, en, { provider: 'Pružalac', model: 'Model', effort: 'Napor', defaultEffort: 'Zadano', instruction: 'Dodatna uputa', instructionPlaceholder: 'Dodajte neobaveznu uputu', send: 'Pošalji', append: 'Dodaj', interrupt: 'Prekini', install: 'Instaliraj', cancel: 'Otkaži', installTitle: 'Instaliraj pružaoca', close: 'Zatvori', history: 'Historija sesija', records: 'zapisa', loading: 'Učitavanje…', noSessions: 'Još nema sesija', orphan: 'Izvorni čvor više ne postoji; historija je sačuvana.', requested: 'Zatraženo', effective: 'Primijenjeno', artifacts: 'Rezultati', copySessionId: 'Kopiraj ID sesije', loadMore: 'Učitaj više', missing: 'Nedostaje', installed_inactive: 'Instalirano', ready: 'Spremno', auth_required: 'Potrebna prijava', degraded: 'Ograničeno', incompatible: 'Nekompatibilno', failed: 'Neuspjelo', loadingState: 'Učitavanje', unavailable: 'Nedostupno', dirty: 'Sačuvajte mapu prije slanja.', active: 'Pokrenuto', idle: 'Neaktivno', error: 'Greška sesije', copyDone: 'Kopirano' }),
			tr: Object.assign({}, en, { provider: 'Sağlayıcı', model: 'Model', effort: 'Çaba', defaultEffort: 'Varsayılan', instruction: 'Ek talimat', instructionPlaceholder: 'İsteğe bağlı talimat ekleyin', send: 'Gönder', append: 'Ekle', interrupt: 'Durdur', install: 'Yükle', cancel: 'İptal', installTitle: 'Sağlayıcıyı yükle', close: 'Kapat', history: 'Oturum geçmişi', records: 'kayıt', loading: 'Yükleniyor…', noSessions: 'Henüz oturum yok', orphan: 'Özgün düğüm artık yok; geçmiş korundu.', requested: 'İstenen', effective: 'Etkin', artifacts: 'Çıktılar', copySessionId: 'Oturum kimliğini kopyala', loadMore: 'Daha fazla yükle', missing: 'Eksik', installed_inactive: 'Yüklendi', ready: 'Hazır', auth_required: 'Oturum açma gerekli', degraded: 'Kısıtlı', incompatible: 'Uyumsuz', failed: 'Başarısız', loadingState: 'Yükleniyor', unavailable: 'Kullanılamıyor', dirty: 'Göndermeden önce zihin haritasını kaydedin.', active: 'Çalışıyor', idle: 'Boşta', error: 'Oturum hatası', copyDone: 'Kopyalandı' }),
			ar: Object.assign({}, en, { provider: 'المزوّد', model: 'النموذج', effort: 'مستوى الاستدلال', defaultEffort: 'افتراضي', instruction: 'تعليمات إضافية', instructionPlaceholder: 'أضف تعليمات اختيارية', send: 'إرسال', append: 'إضافة', interrupt: 'إيقاف', install: 'تثبيت', cancel: 'إلغاء', installTitle: 'تثبيت المزوّد', close: 'إغلاق', history: 'سجل الجلسات', records: 'سجلات', loading: 'جارٍ التحميل…', noSessions: 'لا توجد جلسات بعد', orphan: 'العقدة الأصلية غير موجودة؛ تم الاحتفاظ بالسجل.', requested: 'المطلوب', effective: 'الفعلي', artifacts: 'المخرجات', copySessionId: 'نسخ معرّف الجلسة', loadMore: 'تحميل المزيد', missing: 'غير مثبت', installed_inactive: 'مثبت', ready: 'جاهز', auth_required: 'تسجيل الدخول مطلوب', degraded: 'محدود', incompatible: 'غير متوافق', failed: 'فشل', loadingState: 'جارٍ التحميل', unavailable: 'غير متاح', dirty: 'احفظ الخريطة الذهنية قبل الإرسال.', active: 'قيد التشغيل', idle: 'خامل', error: 'خطأ في الجلسة', copyDone: 'تم النسخ' })
		};
		var providerInstallTranslations = {
			de: { retry: 'Erneut versuchen', installOpening: 'Provider Runtime wird heruntergeladen', installWaiting: 'Provider Runtime wird installiert', installVerifying: 'Provider Runtime wird geprüft', installCompleted: 'Erfolgreich installiert', installFailed: 'Installation fehlgeschlagen' },
			es: { retry: 'Reintentar', installOpening: 'Descargando Provider Runtime', installWaiting: 'Instalando Provider Runtime', installVerifying: 'Verificando Provider Runtime', installCompleted: 'Instalado correctamente', installFailed: 'Error de instalación' },
			fr: { retry: 'Réessayer', installOpening: 'Téléchargement de Provider Runtime', installWaiting: 'Installation de Provider Runtime', installVerifying: 'Vérification de Provider Runtime', installCompleted: 'Installation réussie', installFailed: 'Échec de l’installation' },
			it: { retry: 'Riprova', installOpening: 'Download di Provider Runtime', installWaiting: 'Installazione di Provider Runtime', installVerifying: 'Verifica di Provider Runtime', installCompleted: 'Installazione completata', installFailed: 'Installazione non riuscita' },
			cs: { retry: 'Zkusit znovu', installOpening: 'Stahování Provider Runtimeu', installWaiting: 'Instalace Provider Runtimeu', installVerifying: 'Ověřování Provider Runtimeu', installCompleted: 'Úspěšně nainstalováno', installFailed: 'Instalace selhala' },
			hu: { retry: 'Újra', installOpening: 'Provider Runtime letöltése', installWaiting: 'Provider Runtime telepítése', installVerifying: 'Provider Runtime ellenőrzése', installCompleted: 'Sikeresen telepítve', installFailed: 'A telepítés sikertelen' },
			ja: { retry: '再試行', installOpening: 'Provider Runtime をダウンロード中', installWaiting: 'Provider Runtime をインストール中', installVerifying: 'Provider Runtime を確認中', installCompleted: 'インストールしました', installFailed: 'インストールに失敗しました' },
			ko: { retry: '다시 시도', installOpening: 'Provider Runtime 다운로드 중', installWaiting: 'Provider Runtime 설치 중', installVerifying: 'Provider Runtime 확인 중', installCompleted: '설치 완료', installFailed: '설치 실패' },
			pl: { retry: 'Ponów', installOpening: 'Pobieranie Provider Runtime', installWaiting: 'Instalowanie Provider Runtime', installVerifying: 'Weryfikowanie Provider Runtime', installCompleted: 'Zainstalowano pomyślnie', installFailed: 'Instalacja nie powiodła się' },
			pt: { retry: 'Tentar novamente', installOpening: 'A transferir o Provider Runtime', installWaiting: 'A instalar o Provider Runtime', installVerifying: 'A verificar o Provider Runtime', installCompleted: 'Instalado com êxito', installFailed: 'Falha na instalação' },
			ru: { retry: 'Повторить', installOpening: 'Загрузка Provider Runtime', installWaiting: 'Установка Provider Runtime', installVerifying: 'Проверка Provider Runtime', installCompleted: 'Успешно установлено', installFailed: 'Ошибка установки' },
			'zh-cn': { retry: '重试', installOpening: '正在下载 Provider Runtime', installWaiting: '正在安装 Provider Runtime', installVerifying: '正在验证 Provider Runtime', installCompleted: '安装成功', installFailed: '安装失败' },
			'zh-tw': { retry: '重試', installOpening: '正在下載 Provider Runtime', installWaiting: '正在安裝 Provider Runtime', installVerifying: '正在驗證 Provider Runtime', installCompleted: '安裝成功', installFailed: '安裝失敗' },
			no: { retry: 'Prøv igjen', installOpening: 'Laster ned Provider Runtime', installWaiting: 'Installerer Provider Runtime', installVerifying: 'Kontrollerer Provider Runtime', installCompleted: 'Installert', installFailed: 'Installasjonen mislyktes' },
			br: { retry: 'Tentar novamente', installOpening: 'Baixando Provider Runtime', installWaiting: 'Instalando Provider Runtime', installVerifying: 'Verificando Provider Runtime', installCompleted: 'Instalado com sucesso', installFailed: 'Falha na instalação' },
			th: { retry: 'ลองอีกครั้ง', installOpening: 'กำลังดาวน์โหลด Provider Runtime', installWaiting: 'กำลังติดตั้ง Provider Runtime', installVerifying: 'กำลังตรวจสอบ Provider Runtime', installCompleted: 'ติดตั้งสำเร็จ', installFailed: 'ติดตั้งไม่สำเร็จ' },
			da: { retry: 'Prøv igen', installOpening: 'Downloader Provider Runtime', installWaiting: 'Installerer Provider Runtime', installVerifying: 'Kontrollerer Provider Runtime', installCompleted: 'Installeret', installFailed: 'Installationen mislykkedes' },
			bs: { retry: 'Pokušaj ponovo', installOpening: 'Preuzimanje Provider Runtimea', installWaiting: 'Instaliranje Provider Runtimea', installVerifying: 'Provjera Provider Runtimea', installCompleted: 'Uspješno instalirano', installFailed: 'Instalacija nije uspjela' },
			tr: { retry: 'Yeniden dene', installOpening: 'Provider Runtime indiriliyor', installWaiting: 'Provider Runtime yükleniyor', installVerifying: 'Provider Runtime doğrulanıyor', installCompleted: 'Başarıyla yüklendi', installFailed: 'Yükleme başarısız' },
			ar: { retry: 'إعادة المحاولة', installOpening: 'جارٍ تنزيل Provider Runtime', installWaiting: 'جارٍ تثبيت Provider Runtime', installVerifying: 'جارٍ التحقق من Provider Runtime', installCompleted: 'تم التثبيت بنجاح', installFailed: 'فشل التثبيت' }
		};
		var mcpConnectionTranslations = {
			'zh-cn': { mcpReady: 'KM MCP 已连接', mcpConnecting: '正在连接 KM MCP…', mcpReconnecting: '正在重连 KM MCP…', mcpUnavailable: 'KM MCP 不可用', reconnectMcp: '立即重连', mcpOperationFailed: 'KM MCP 连接已中断。请重连后重试刚才的操作。', mcpReconnectedRetry: 'KM MCP 已恢复，请重试刚才的操作。' },
			'zh-tw': { mcpReady: 'KM MCP 已連線', mcpConnecting: '正在連線 KM MCP…', mcpReconnecting: '正在重新連線 KM MCP…', mcpUnavailable: 'KM MCP 無法使用', reconnectMcp: '立即重連', mcpOperationFailed: 'KM MCP 連線已中斷。請重新連線後再試一次。', mcpReconnectedRetry: 'KM MCP 已恢復，請重試剛才的操作。' }
		};
		Object.keys(uiTranslations).forEach(function(language) {
			Object.assign(dictionaries[language], uiTranslations[language]);
		});
		Object.keys(providerInstallTranslations).forEach(function(language) {
			Object.assign(dictionaries[language], providerInstallTranslations[language]);
		});
		Object.keys(mcpConnectionTranslations).forEach(function(language) {
			Object.assign(dictionaries[language], mcpConnectionTranslations[language]);
		});

		return {
			t: function(key) {
				var language = String(config.get('lang') || 'en').toLowerCase().replace('_', '-');
				var dictionary = dictionaries[language] || dictionaries.en;
				return dictionary[key] || dictionaries.en[key] || key;
			},
			languages: Object.keys(dictionaries)
		};
	}
]);

angular.module('kityminderEditor').filter('agentSessionText', [
	'agentSessionI18n',
	function(agentSessionI18n) {
		return function(key) { return agentSessionI18n.t(key); };
	}
]);
